native_packages:
  - plasma-desktop
  - dolphin
  - sddm
  - networkmanager
  - kitty
  - firefox
  - bluez
  - bluez-utils
  - nvidia-open
  - nvidia-utils
  - git
  - sudo
  - btrfs-progs
  - cups
  - cups-pk-helper
  - ethtool
  - fcitx5
  - fcitx5-configtool
  - fcitx5-gtk
  - fcitx5-qt
  - fuzzel
  - grim
  - gst-plugin-pipewire
  - hypridle
  - hyprland
  - hyprpaper
  - libpulse
  - mako
  - nload
  - noto-fonts-cjk
  - openssh
  - ouch
  - pipewire
  - pipewire-alsa
  - pipewire-jack
  - pipewire-pulse
  - rcm
  - slurp
  - snap-pac
  - snapper
  - sof-firmware
  - system-config-printer
  - waybar
  - wdisplays
  - wiremix
  - wireplumber
  - wl-clipboard
  - wlr-randr
  - wpa_supplicant
  - zram-generator
  - zsh
