AddPackage networkmanager
AddPackage bluez
AddPackage bluez-utils
AddPackage pipewire
AddPackage pipewire-alsa
AddPackage pipewire-jack
AddPackage pipewire-pulse
AddPackage wireplumber
AddPackage sddm
AddPackage cups
AddPackage cups-pk-helper
AddPackage hypridle
AddPackage mako
AddPackage snapper
AddPackage snap-pac
AddPackage zram-generator
AddPackage openssh
AddPackage wpa_supplicant
