listener {
    # 10分（600秒）放置されたら画面をロック（hyprlock）する
    timeout = 600
    on-timeout = hyprlock
}

listener {
    # 30分（1800秒）放置されたらシステムをサスペンド（スリープ）する
    timeout = 1800
    on-timeout = systemctl suspend
}
